#lang datalog

likes(amy, susan).
likes(susan, amy).
likes(amy, mark).
likes(lola, mark).
likes(brewster, mark).
likes(brewster, lucky).
likes(amy, tyrion).
likes(tyrion, amy).
likes(susan, tyrion).
likes(tyrion, susan).
likes(tyrion, tyrion).

mutual(A, B) :- likes(A, B), likes(B, A).

popular(A) :- likes(X, A), likes(Y, A), likes(Z, A), X != Z, Y != X, Z !=  Y.

likesThemselves(A) :- likes(A, A).